### ISSUE TITLE
ERROR template: msmtprc.tmpl:8:7: executing "msmtprc.tmpl" at <getv "/php/smtp">: error calling getv: key does not exist Updating apache/php configuration files.

### ISSUE THREAD

**Issue by wpjCode** [antage/docker-apache2-php7#1]
ERROR template: msmtprc.tmpl:8:7: executing "msmtprc.tmpl" at <getv "/php/smtp">: error calling getv: key does not exist
Updating apache/php configuration files..
I see you say "Required variables", How to use?

**Comment by antage** [comment]
```
docker run -e PHP_SMTP=172.17.0.1 -e PHP_SMTP_FROM=noreply@localhost antage/apache2-php7
```

**Comment by wpjCode** [comment]
Thank,i try , it's OK.
But in container I have change '/etc/appache2/apache.conf'...restart container .The config file is  restore.

**Comment by antage** [comment]
`/etc/apache2/apach2.conf` isn't permanent. It's generated from a template.

**Comment by wpjCode** [comment]
I need to add code "IncludeOptional sites-enabled/*.conf" in file apache2.conf. How to do？

**Comment by wpjCode** [comment]
I saw, you docker file, template is in /etc/confd/templates, It's you change apache code? You are so good, Use Go Language? I want to know.

**Comment by antage** [comment]
Configuration is generated from templates with [confd](https://github.com/kelseyhightower/confd).
If you want to change templates you need fork the repository and make own docker image.

**Comment by wpjCode** [comment]
Thank you very much.I find some Information: '/etc/confd' is template folder ,I am delete apache file.
